version: '3'

services:
  shared:
    build: ./src/shared
    image: io-shared
  admin:
    build: ./src/admin
    image: io-admin
    container_name: io-admin
    init: true
    restart: always
    ports:
      - "5090:80"
    depends_on:
      - mongo
      - shared
  api:
    build: ./src/api
    image: io-api
    container_name: io-api
    init: true
    restart: always
    ports:
      - "5001:80"
    depends_on:
      - shared
  chat:
    build: ./src/chat
    image: io-chat
    container_name: io-api
    init: true
    restart: always
    ports:
      - "5050:80"
    volumes:
      - ./assets:/app/dist/assets
    depends_on:
      - hub
      - api
      - mongo
      - shared
  chron:
    build: ./src/chron
    image: io-chron
    container_name: io-chron
    init: true
    restart: always
    ports:
      - "5080:80"
    depends_on:
      - api
      - hub
      - shared
  hub:
    build: ./src/hub
    image: io-hub
    container_name: io-hub
    init: true
    restart: always
    ports:
      - "5060:80"
    depends_on:
      - shared
  logger:
    build: ./src/logger
    image: io-logger
    container_name: io-logger
    init: true
    restart: always
    depends_on:
      - hub
      - mongo
      - shared
  overlay:
    build: ./src/overlay
    image: io-overlay
    container_name: io-overlay
    init: true
    restart: always
    ports:
      - "5000:80"
    volumes:
      - ./assets:/app/dist/wwwroot/assets
    depends_on:
      - hub
      - shared
  streamnotes:
    build: ./src/stream-notes
    image: io-streamnotes
    container_name: io-streamnotes
    init: true
    restart: always
    depends_on:
      - api
      - hub
      - shared
  user:
    build: ./src/user
    image: io-user
    container_name: io-user
    init: true
    restart: always
    ports:
      - "5070:80"
    depends_on:
      - api
      - mongo
      - shared
  webhooks:
    build: ./src/webhooks
    image: io-webhooks
    container_name: io-webhooks
    init: true
    restart: always
    ports:
      - "5005:80"
    depends_on:
      - hub
      - user
      - shared
  mongo:
    image: mongo:4.0
    container_name: mongo-db
    restart: always
    volumes:
      - "mongodata:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongoex:
    image: mongo-express:0.49.0
    container_name: mongo-admin-interface
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
volumes:
  mongodata:
